version: '3'
services:
  rbc:
    build:
      context: ./rbc
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql

  weather:
    build:
      context: ./weather
      dockerfile: Dockerfile
    ports:
      - "8070:8070"

  prediction:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd

pgadmin:
  image: dpage/pgadmin4
  ports:
    - "5432:5432"
  depends_on:
    - dbpostgresql
  environment:
    - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
    - PGADMIN_DEFAULT_PASSWORD=postgres
  networks:
    vpcbr:
      ipv4_address: 10.5.0.9