version: '3'
services:
  rbkapp:
    build:
      context: ./rbkapp
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  weatherapp:
    build:
      context: ./weatherapp
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  predictionapp:
    build:
      context: ./predictionapp
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16