version: '3'
services:
  rbc:
    image: docker-rbc
    build:
      context: ./RbkApp
    ports:
      - "8050:8050"
    depends_on:
      - dbpostgresql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20

  weather:
    image: docker-weather
    build:
      context: ./WeatherApp
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.17

  prediction:
    image: docker-prediction
    build:
      context: ./PredictionApp
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.18

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
    networks:
      vpcbr:
        ipv4_address: 10.5.0.19


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.21

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.22
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.16
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.16/24