global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'rbc_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['rbc:8050']
  - job_name: 'weather_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['weather:8070']
  - job_name: 'prediction_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prediction:8090']