---
- hosts: rbc-server
  remote_user: mftiedu
  become: yes

  vars:
    ansible_become_user: root
    ansible_become_password: cHONtic

  tasks:
    - name: delete previous directory
      shell: rm -rf ./edu/vikstr

    - name: make a directory for rbc module
      shell: mkdir edu/vikstr/


    - name: make a directory for rbc module
      shell: mkdir edu/vikstr/rbc

    - name: make a directory for rbc module
      shell: mkdir edu/vikstr/rbc/target

    - name: copy rbc module
      copy:
        src: ../RbkApp/target/RbkApp-0.1.0.jar
        dest: edu/vikstr/rbc/target

    - name: copy rbc Dockerfile module
      copy:
        src: ../RbkApp/Dockerfile
        dest: edu/vikstr/rbc/
        mode: 0777


    - name: copy docker-compose rbc module
      copy:
        src: ./docker-compose-rbc.yml
        dest: edu/vikstr/

    - name: run a compose rbc file
      shell: sudo docker-compose -f ./edu/vikstr/docker-compose-rbc.yml up -d

- hosts: weather-predict-server
  remote_user: edumfti
  become: yes
  tasks: 

    - name: delete previous directory
      shell: rm -rf ./edu/vikstr

    - name: make a directory
      shell: mkdir edu/vikstr/

    - name: make a directory for predict module
      shell: mkdir edu/vikstr/predict

    - name: make a directory for predict module
      shell: mkdir edu/vikstr/predict/target

    - name: make a directory for weather module
      shell: mkdir edu/vikstr/weather

    - name: make a directory for weather module
      shell: mkdir edu/vikstr/weather/target

    - name: copy weather module
      copy:
        src: ../WeatherApp/target/WeatherApp-0.1.0.jar
        dest: edu/vikstr/weather/target

    - name: copy wether Dockerfile module
      copy:
        src: ../WeatherApp/Dockerfile
        dest: edu/vikstr/weather/
        mode: 0777

    - name: copy predict module
      copy:
        src: ../PredictionApp/target/PredictionApp-0.1.0.jar
        dest: edu/vikstr/predict/target

    - name: copy predict Dockerfile module
      copy:
        src: ../PredictionApp/Dockerfile
        dest: edu/vikstr/predict/
        mode: 0777

    - name: copy docker-compose weather-prediction module
      copy:
        src: ./docker-compose-weather-prediction.yml
        dest: edu/vikstr/

    - name: run a compose predict weather file
      shell: docker-compose -f ./edu/vikstr/docker-compose-weather-prediction.yml up -d
