version: '3'
services:
  weather:
    build:
      context: ./weather
      dockerfile: Dockerfile
    ports:
      - "8070:8070"

  predict:
    build:
      context: ./predict
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
