version: '3'
services:
  rbc:
    image: g_rbk_app
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql
  ml:
    image: g_prediction_app
    ports:
      - "8090:8090"
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
