version: '3'
services:
  rbc:
    build: 
      context: ./rbc
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql
  

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5032:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5051:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
