- hosts: rbc-and-ml-server
  remote_user: mftiedu
  become: yes

  vars:
    ansible_become_user: root
    ansible_become_password: cHONtic
  
  tasks:
    - name: delete previous directory
      shell: rm -rf ./edu/vikstr

    - name: make a directory for lab-4
      shell: mkdir edu/vikstr
      #ignore_errors: True

    - name: make a directory for rbkapp module
      shell: mkdir edu/vikstr/rbkapp
      #ignore_errors: True

    - name: make a directory for predictionapp module
      shell: mkdir edu/vikstr/predictionapp
      #ignore_errors: True

    - name: copy rbkapp module
      copy:
        src: ./rbkapp/RbkApp-0.1.0.jar
        dest: edu/vikstr/rbkapp/  

    - name: copy predictionapp module
      copy:
        src: ./predictionapp/PredictionApp-0.1.0.jar
        dest: edu/vikstr/predictionapp/
  
    - name: copy Dockerfile for rbkapp module
      copy:
        src: ./rbkapp/Dockerfile
        dest: edu/vikstr/rbkapp/

    - name: copy Dockerfile for predictionapp module
      copy:
        src: ./predictionapp/Dockerfile
        dest: edu/vikstr/predictionapp/

    - name: load image for rbkapp module
      docker_image:
        name: g_rbk_app
        path: ./edu/vikstr/rbkapp
        source: build

    - name: load image for predictionapp module
      docker_image:
        name: g_prediction_app
        path: ./edu/vikstr/predictionapp
        source: build

    - name: copy rbc-prediction compose file
      copy:
        src: ./docker-compose-rbc-prediction.yml
        dest: edu/vikstr/
  
    - name: run a compose file
      shell: sudo docker-compose -f ./edu/vikstr/docker-compose-rbc-prediction.yml up -d
